"""add_learning_mode_selected_course_to_profiles

Revision ID: 3df71d87b2be
Revises: 
Create Date: 2026-01-17 15:06:43.545887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3df71d87b2be'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('path_adjustments',
    sa.Column('adjustment_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('path_id', sa.Integer(), nullable=True),
    sa.Column('adjustment_type', sa.String(length=50), nullable=True),
    sa.Column('target_module_id', sa.Integer(), nullable=True),
    sa.Column('target_lesson_id', sa.Integer(), nullable=True),
    sa.Column('target_project_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('ai_reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['path_id'], ['learning_paths.path_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_lesson_id'], ['lessons.lesson_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_module_id'], ['modules.module_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_project_id'], ['projects.project_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('adjustment_id')
    )
    op.create_index(op.f('ix_path_adjustments_path_id'), 'path_adjustments', ['path_id'], unique=False)
    op.create_index(op.f('ix_path_adjustments_user_id'), 'path_adjustments', ['user_id'], unique=False)
    op.create_table('user_progress',
    sa.Column('progress_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('lesson_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('NOT_STARTED', 'IN_PROGRESS', 'COMPLETED', name='progressstatus'), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('time_spent_seconds', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('lesson_id IS NOT NULL OR project_id IS NOT NULL', name='check_lesson_or_project'),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.lesson_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('progress_id')
    )
    op.create_index('idx_user_progress_status', 'user_progress', ['user_id', 'status'], unique=False)
    op.create_index(op.f('ix_user_progress_lesson_id'), 'user_progress', ['lesson_id'], unique=False)
    op.create_index(op.f('ix_user_progress_project_id'), 'user_progress', ['project_id'], unique=False)
    op.create_index(op.f('ix_user_progress_status'), 'user_progress', ['status'], unique=False)
    op.create_index(op.f('ix_user_progress_user_id'), 'user_progress', ['user_id'], unique=False)
    op.drop_index(op.f('ix_assessment_responses_question_id'), table_name='assessment_responses')
    op.drop_index(op.f('ix_assessment_responses_user_id'), table_name='assessment_responses')
    op.drop_table('assessment_responses')
    op.drop_index(op.f('idx_module_progress_user_module'), table_name='module_progress')
    op.drop_index(op.f('ix_module_progress_module_id'), table_name='module_progress')
    op.drop_index(op.f('ix_module_progress_user_id'), table_name='module_progress')
    op.drop_table('module_progress')
    op.drop_index(op.f('idx_behavioral_signals_type'), table_name='behavioral_signals')
    op.drop_index(op.f('idx_behavioral_signals_user'), table_name='behavioral_signals')
    op.drop_index(op.f('ix_behavioral_signals_signal_type'), table_name='behavioral_signals')
    op.drop_index(op.f('ix_behavioral_signals_user_id'), table_name='behavioral_signals')
    op.drop_table('behavioral_signals')
    op.drop_index(op.f('idx_lesson_progress_user_lesson'), table_name='lesson_progress')
    op.drop_index(op.f('ix_lesson_progress_lesson_id'), table_name='lesson_progress')
    op.drop_index(op.f('ix_lesson_progress_user_id'), table_name='lesson_progress')
    op.drop_table('lesson_progress')
    op.drop_index(op.f('idx_project_submissions_module'), table_name='project_submissions')
    op.drop_index(op.f('idx_project_submissions_status'), table_name='project_submissions')
    op.drop_index(op.f('idx_project_submissions_user_project'), table_name='project_submissions')
    op.drop_index(op.f('ix_project_submissions_module_id'), table_name='project_submissions')
    op.drop_index(op.f('ix_project_submissions_project_id'), table_name='project_submissions')
    op.drop_index(op.f('ix_project_submissions_user_id'), table_name='project_submissions')
    op.drop_table('project_submissions')
    op.drop_index(op.f('idx_assessment_submissions_module'), table_name='assessment_submissions')
    op.drop_index(op.f('idx_assessment_submissions_user_question'), table_name='assessment_submissions')
    op.drop_index(op.f('ix_assessment_submissions_module_id'), table_name='assessment_submissions')
    op.drop_index(op.f('ix_assessment_submissions_question_id'), table_name='assessment_submissions')
    op.drop_index(op.f('ix_assessment_submissions_user_id'), table_name='assessment_submissions')
    op.drop_table('assessment_submissions')
    op.drop_index(op.f('ix_assessment_questions_module_id'), table_name='assessment_questions')
    op.drop_table('assessment_questions')
    op.add_column('user_profiles', sa.Column('learning_mode', sa.Enum('BOOTCAMP', 'SELF_PACED', name='learningmode'), nullable=True))
    op.add_column('user_profiles', sa.Column('selected_course_id', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_user_profiles_learning_mode'), 'user_profiles', ['learning_mode'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_profiles_learning_mode'), table_name='user_profiles')
    op.drop_column('user_profiles', 'selected_course_id')
    op.drop_column('user_profiles', 'learning_mode')
    op.create_table('assessment_questions',
    sa.Column('question_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('module_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('question_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('question_type', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('difficulty_level', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('options', postgresql.ARRAY(sa.VARCHAR(length=500)), autoincrement=False, nullable=True),
    sa.Column('correct_answer', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('explanation', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('points', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['module_id'], ['modules.module_id'], name=op.f('assessment_questions_module_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('question_id', name=op.f('assessment_questions_pkey'))
    )
    op.create_index(op.f('ix_assessment_questions_module_id'), 'assessment_questions', ['module_id'], unique=False)
    op.create_table('assessment_submissions',
    sa.Column('submission_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('question_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('module_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('response_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_correct', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('time_taken_seconds', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('attempts', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('confidence_level', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('deadline_status', postgresql.ENUM('FIRST_DEADLINE', 'SECOND_DEADLINE', 'LATE', 'NOT_SUBMITTED', name='deadlinestatus'), autoincrement=False, nullable=True),
    sa.Column('points_earned', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('submitted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['module_id'], ['modules.module_id'], name=op.f('assessment_submissions_module_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['assessment_questions.question_id'], name=op.f('assessment_submissions_question_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('assessment_submissions_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('submission_id', name=op.f('assessment_submissions_pkey'))
    )
    op.create_index(op.f('ix_assessment_submissions_user_id'), 'assessment_submissions', ['user_id'], unique=False)
    op.create_index(op.f('ix_assessment_submissions_question_id'), 'assessment_submissions', ['question_id'], unique=False)
    op.create_index(op.f('ix_assessment_submissions_module_id'), 'assessment_submissions', ['module_id'], unique=False)
    op.create_index(op.f('idx_assessment_submissions_user_question'), 'assessment_submissions', ['user_id', 'question_id'], unique=False)
    op.create_index(op.f('idx_assessment_submissions_module'), 'assessment_submissions', ['module_id'], unique=False)
    op.create_table('project_submissions',
    sa.Column('submission_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('module_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('solution_url', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('is_approved', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('deadline_status', postgresql.ENUM('FIRST_DEADLINE', 'SECOND_DEADLINE', 'LATE', 'NOT_SUBMITTED', name='deadlinestatus'), autoincrement=False, nullable=True),
    sa.Column('points_earned', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('reviewer_feedback', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('submitted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('reviewed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['module_id'], ['modules.module_id'], name=op.f('project_submissions_module_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], name=op.f('project_submissions_project_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('project_submissions_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('submission_id', name=op.f('project_submissions_pkey'))
    )
    op.create_index(op.f('ix_project_submissions_user_id'), 'project_submissions', ['user_id'], unique=False)
    op.create_index(op.f('ix_project_submissions_project_id'), 'project_submissions', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_submissions_module_id'), 'project_submissions', ['module_id'], unique=False)
    op.create_index(op.f('idx_project_submissions_user_project'), 'project_submissions', ['user_id', 'project_id'], unique=False)
    op.create_index(op.f('idx_project_submissions_status'), 'project_submissions', ['status'], unique=False)
    op.create_index(op.f('idx_project_submissions_module'), 'project_submissions', ['module_id'], unique=False)
    op.create_table('lesson_progress',
    sa.Column('progress_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('lesson_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('completed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('time_spent_minutes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.lesson_id'], name=op.f('lesson_progress_lesson_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('lesson_progress_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('progress_id', name=op.f('lesson_progress_pkey'))
    )
    op.create_index(op.f('ix_lesson_progress_user_id'), 'lesson_progress', ['user_id'], unique=False)
    op.create_index(op.f('ix_lesson_progress_lesson_id'), 'lesson_progress', ['lesson_id'], unique=False)
    op.create_index(op.f('idx_lesson_progress_user_lesson'), 'lesson_progress', ['user_id', 'lesson_id'], unique=False)
    op.create_table('behavioral_signals',
    sa.Column('signal_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('signal_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('signal_value', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('device_type', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('recorded_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('behavioral_signals_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('signal_id', name=op.f('behavioral_signals_pkey'))
    )
    op.create_index(op.f('ix_behavioral_signals_user_id'), 'behavioral_signals', ['user_id'], unique=False)
    op.create_index(op.f('ix_behavioral_signals_signal_type'), 'behavioral_signals', ['signal_type'], unique=False)
    op.create_index(op.f('idx_behavioral_signals_user'), 'behavioral_signals', ['user_id'], unique=False)
    op.create_index(op.f('idx_behavioral_signals_type'), 'behavioral_signals', ['signal_type'], unique=False)
    op.create_table('module_progress',
    sa.Column('progress_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('module_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('lessons_completed', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_lessons', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('assessments_passed', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_assessments', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('projects_approved', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_projects', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_points_earned', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('module_completed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('last_updated', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['module_id'], ['modules.module_id'], name=op.f('module_progress_module_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('module_progress_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('progress_id', name=op.f('module_progress_pkey'))
    )
    op.create_index(op.f('ix_module_progress_user_id'), 'module_progress', ['user_id'], unique=False)
    op.create_index(op.f('ix_module_progress_module_id'), 'module_progress', ['module_id'], unique=False)
    op.create_index(op.f('idx_module_progress_user_module'), 'module_progress', ['user_id', 'module_id'], unique=False)
    op.create_table('assessment_responses',
    sa.Column('response_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('question_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('response_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_correct', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('time_taken_seconds', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('attempts', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('confidence_level', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['assessment_questions.question_id'], name=op.f('assessment_responses_question_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('assessment_responses_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('response_id', name=op.f('assessment_responses_pkey'))
    )
    op.create_index(op.f('ix_assessment_responses_user_id'), 'assessment_responses', ['user_id'], unique=False)
    op.create_index(op.f('ix_assessment_responses_question_id'), 'assessment_responses', ['question_id'], unique=False)
    op.drop_index(op.f('ix_user_progress_user_id'), table_name='user_progress')
    op.drop_index(op.f('ix_user_progress_status'), table_name='user_progress')
    op.drop_index(op.f('ix_user_progress_project_id'), table_name='user_progress')
    op.drop_index(op.f('ix_user_progress_lesson_id'), table_name='user_progress')
    op.drop_index('idx_user_progress_status', table_name='user_progress')
    op.drop_table('user_progress')
    op.drop_index(op.f('ix_path_adjustments_user_id'), table_name='path_adjustments')
    op.drop_index(op.f('ix_path_adjustments_path_id'), table_name='path_adjustments')
    op.drop_table('path_adjustments')
    # ### end Alembic commands ###
