#!/usr/bin/python3
"""AI Mentor Feedback: persisted messages generated by the smart-trigger mentor agent.

One table backs three triggers (quiz score review, project-start guidance,
inactivity check-in) so the same row set can serve as both the student's
"AI Mentor Feedback" dashboard feed and the dedup ledger that stops a trigger
from firing twice for the same event.
"""
from datetime import datetime, timezone
from sqlalchemy import Column, Integer, String, Text, DateTime, Float, ForeignKey, Index
from db.base import Base


class AIMentorFeedback(Base):
    """A single AI-generated mentor message shown to a student."""

    __tablename__ = "ai_mentor_feedback"

    feedback_id = Column(Integer, primary_key=True, autoincrement=True)
    user_id = Column(String(36), ForeignKey("users.id", ondelete="CASCADE"), index=True, nullable=False)

    # 'quiz_encouragement' | 'quiz_correction' | 'project_guidance' | 'inactivity_checkin'
    category = Column(String(30), nullable=False, index=True)

    title = Column(String(200), nullable=False)
    message = Column(Text, nullable=False)

    module_id = Column(Integer, ForeignKey("modules.module_id", ondelete="CASCADE"), nullable=True, index=True)
    project_id = Column(Integer, ForeignKey("projects.project_id", ondelete="CASCADE"), nullable=True, index=True)

    # Denormalized snapshot of the module/project/quiz title at generation time,
    # so the dashboard feed reads correctly even if the source content changes later.
    context_title = Column(String(255), nullable=True)
    score_percent = Column(Float, nullable=True)

    created_at = Column(DateTime(timezone=True), default=lambda: datetime.now(timezone.utc), nullable=False)

    __table_args__ = (
        Index("idx_ai_mentor_feedback_user_created", "user_id", "created_at"),
        Index("idx_ai_mentor_feedback_dedup", "user_id", "category", "module_id", "project_id"),
    )
